# Generated by Django 4.0.6 on 2022-07-31 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file_path',
            new_name='file_name',
        ),
    ]
